"""
aiogram MTProto and API error classes.
"""

from __future__ import annotations

from .mtproto import (
    AuthKeyInvalid,
    AuthKeyNotFound,
    AuthKeyUnregistered,
    BadRequest,
    CryptoError,
    FileMigrate,
    FileReferenceExpired,
    FloodWait,
    Forbidden,
    InternalServerError,
    MigrationError,
    MTProtoError,
    NetworkMigrate,
    NotFound,
    PhoneCodeExpired,
    PhoneCodeInvalid,
    PhoneMigrate,
    PhoneNumberInvalid,
    RPCError,
    SessionPasswordNeeded,
    SlowmodeWait,
    TransportError,
    Unauthorized,
    UserMigrate,
    parse_rpc_error,
)

__all__ = (
    "AuthKeyInvalid",
    "AuthKeyNotFound",
    "AuthKeyUnregistered",
    "BadRequest",
    "CryptoError",
    "FileMigrate",
    "FileReferenceExpired",
    "FloodWait",
    "Forbidden",
    "InternalServerError",
    "MTProtoError",
    "MigrationError",
    "NetworkMigrate",
    "NotFound",
    "PhoneCodeExpired",
    "PhoneCodeInvalid",
    "PhoneMigrate",
    "PhoneNumberInvalid",
    "RPCError",
    "SessionPasswordNeeded",
    "SlowmodeWait",
    "TransportError",
    "Unauthorized",
    "UserMigrate",
    "parse_rpc_error",
)
